on-the-route-to-success/config/routes.rb
Rails.application.routes.draw do
  resources :horses
  resources :cars
  resources :airplanes
  resources :trains
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

on-the-route-to-success/app/models/airplane.rb
class Airplane < ApplicationRecord
end

on-the-route-to-success/app/models/car.rb
class Car < ApplicationRecord
end

on-the-route-to-success/app/models/horse.rb
class Horse < ApplicationRecord
end

on-the-route-to-success/app/models/train.rb
class Train < ApplicationRecord
end

on-the-route-to-success/app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
    def index
        @airplanes = Airplane.all
    end
end

on-the-route-to-success/app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
      @cars = Car.all
  end
end

on-the-route-to-success/app/controllers/horses_controller.rb
class HorsesController < ApplicationController
  before_action :set_horse, only: [:show, :edit, :update, :destroy]

  # GET /horses
  def index
    @horses = Horse.all
  end

  # GET /horses/1
  def show
  end

  # GET /horses/new
  def new
    @horse = Horse.new
  end

  # GET /horses/1/edit
  def edit
  end

  # POST /horses
  def create
    @horse = Horse.new(horse_params)

    if @horse.save
      redirect_to @horse, notice: 'Horse was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /horses/1
  def update
    if @horse.update(horse_params)
      redirect_to @horse, notice: 'Horse was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /horses/1
  def destroy
    @horse.destroy
    redirect_to horses_url, notice: 'Horse was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horse
      @horse = Horse.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def horse_params
      params.require(:horse).permit(:name)
    end
end

on-the-route-to-success/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
    def index
        @trains = Train.all
    end
end

on-the-route-to-success/app/helpers/cars_helper.rb
module CarsHelper
end

on-the-route-to-success/app/helpers/horses_helper.rb
module HorsesHelper
end

on-the-route-to-success/app/views/airplanes/index.html.erb
<h1>Airplanes#index</h1>
<p>Find me in app/views/airplanes/index.html.erb</p>

<% @airplanes.each do |airplane| %>
  <tr>
    <td><%= airplane.name %></td>
    <td><%= link_to 'Show', airplane %></td>
    <td><%= link_to 'Edit', edit_airplane_path(airplane) %></td>
    <td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

on-the-route-to-success/app/views/horses/_form.html.erb
<%= form_with(model: horse, local: true) do |form| %>
  <% if horse.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(horse.errors.count, "error") %> prohibited this horse from being saved:</h2>

      <ul>
      <% horse.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

on-the-route-to-success/app/views/horses/edit.html.erb
<h1>Editing Horse</h1>

<%= render 'form', horse: @horse %>

<%= link_to 'Show', @horse %> |
<%= link_to 'Back', horses_path %>

on-the-route-to-success/app/views/horses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Horses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @horses.each do |horse| %>
      <tr>
        <td><%= horse.name %></td>
        <td><%= link_to 'Show', horse %></td>
        <td><%= link_to 'Edit', edit_horse_path(horse) %></td>
        <td><%= link_to 'Destroy', horse, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Horse', new_horse_path %>

on-the-route-to-success/app/views/horses/new.html.erb
<h1>New Horse</h1>

<%= render 'form', horse: @horse %>

<%= link_to 'Back', horses_path %>

on-the-route-to-success/app/views/horses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @horse.name %>
</p>

<%= link_to 'Edit', edit_horse_path(@horse) %> |
<%= link_to 'Back', horses_path %>

on-the-route-to-success/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>